services:
  db:
    image: postgres:latest
    container_name: academic-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: academic_admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data: