services:
  db:
    image: postgres:latest
    container_name: academic-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: academic_admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    
  backend:
    build: ./backend
    container_name: academic-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_OWNER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      AUTH_KEY: ${AUTH_KEY}
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: academic-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend


volumes:
  postgres_data:
